name: agrolink
description: AgroLink - Plataforma Agrícola Angolana
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP e API
  http: ^1.2.0
  dio: ^5.4.0

  # Estado global
  provider: ^6.1.2

  # Armazenamento local (token JWT, preferências)
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.0.0

  # Navegação
  go_router: ^13.2.0

  # Mapas e GPS
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  geolocator: ^11.0.0

  # UI
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  intl: ^0.19.0

  # WebSocket (rastreamento em tempo real)
  web_socket_channel: ^2.4.0

  # Ícones e imagens
  cupertino_icons: ^1.0.6
  image_picker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
